### ISSUE TITLE
''npm start'' failing for listed errors

### ISSUE THREAD

**Issue by S-Burns** [primefaces/primeng-quickstart-webpack#10]
| | | +-- concat-stream@1.5.2
| | | | `-- typedarray@0.0.6
| | | +-- form-data@2.0.0
| | | | +-- asynckit@0.4.0
| | | | +-- combined-stream@1.0.5
| | | | |`-- delayed-stream@1.0.0
| | | | `-- mime-types@2.1.12
| | | |`-- mime-db@1.24.0
| | | +-- throwback@1.1.1
| | | `-- tough-cookie@2.3.1
| | +-- popsicle-proxy-agent@3.0.0
| | | +-- http-proxy-agent@1.0.0
| | | | +-- agent-base@2.0.1
| | | |`-- extend@3.0.0
| | | `-- https-proxy-agent@1.0.0
| | +-- popsicle-retry@3.2.1
| | +-- popsicle-status@2.0.0
| | +-- promise-finally@2.2.1
| | +-- rc@1.1.6
| | | +-- deep-extend@0.4.1
| | | +-- ini@1.3.4
| | |`-- strip-json-comments@1.0.4
| | +-- rimraf@2.5.4
| | | `-- glob@7.1.0
| | |   +-- fs.realpath@1.0.0
| | |   +-- inflight@1.0.5
| | |   |`-- wrappy@1.0.2
| | |   +-- minimatch@3.0.3
| | |   | `-- brace-expansion@1.1.6
| | |   |   +-- balanced-match@0.4.2
| | |   |`-- concat-map@0.0.1
| | |   `-- once@1.4.0
| | +-- sort-keys@1.1.2
| | |`-- is-plain-obj@1.1.0
| | +-- string-template@1.0.0
| | +-- strip-bom@2.0.0
| | | `-- is-utf8@0.2.1
| | +-- thenify@3.2.0
| | +-- throat@3.0.0
| | +-- touch@1.0.0
| | |`-- nopt@1.0.10
| | |   `-- abbrev@1.0.9
| | +-- typescript@2.0.3
| |`-- zip-object@0.1.0
| +-- update-notifier@1.0.2
| | +-- boxen@0.6.0
| | | +-- ansi-align@1.1.0
| | | +-- camelcase@2.1.1
| | | +-- cli-boxes@1.0.0
| | | +-- filled-array@1.1.0
| | | +-- string-width@1.0.2
| | | | +-- code-point-at@1.0.0
| | | | `-- is-fullwidth-code-point@1.0.0
| | |`-- widest-line@1.0.0
| | +-- is-npm@1.0.0
| | +-- latest-version@2.0.0
| | | `-- package-json@2.4.0
| | |   +-- got@5.6.0
| | |   | +-- create-error-class@3.0.2
| | |   | |`-- capture-stack-trace@1.0.0
| | |   | +-- duplexer2@0.1.4
| | |   | +-- is-redirect@1.0.0
| | |   | +-- is-retry-allowed@1.1.0
| | |   | +-- is-stream@1.1.0
| | |   | +-- lowercase-keys@1.0.0
| | |   | +-- node-status-codes@1.0.0
| | |   | +-- pinkie-promise@2.0.1
| | |   | | `-- pinkie@2.0.4
| | |   | +-- read-all-stream@3.1.0
| | |   | +-- timed-out@2.0.0
| | |   | +-- unzip-response@1.0.1
| | |   |`-- url-parse-lax@1.0.0
| | |   |   `-- prepend-http@1.0.4
| | |   +-- registry-auth-token@3.0.1
| | |   +-- registry-url@3.1.0
| | |`-- semver@5.3.0
| | +-- lazy-req@1.1.0
| | +-- semver-diff@2.1.0
| | | `-- semver@5.0.3
| |`-- xdg-basedir@2.0.0
| |   `-- os-homedir@1.0.1
| +-- wordwrap@1.0.0
|`-- xtend@4.0.1
`-- webpack@1.13.2
  +-- acorn@3.3.0
  +-- async@1.5.2
  +-- clone@1.0.2
  +-- enhanced-resolve@0.9.1
  |`-- memory-fs@0.2.0
  +-- interpret@0.6.6
  +-- loader-utils@0.2.16
  | +-- big.js@3.1.3
  | +-- emojis-list@2.0.1
  | +-- json5@0.5.0
  | `-- object-assign@4.1.0
  +-- memory-fs@0.3.0
  | +-- errno@0.1.4
  | |`-- prr@0.0.0
  | `-- readable-stream@2.0.6
  |   +-- core-util-is@1.0.2
  |   +-- inherits@2.0.3
  |   +-- isarray@1.0.0
  |   +-- process-nextick-args@1.0.7
  |`-- util-deprecate@1.0.2
  +-- node-libs-browser@0.6.0
  | +-- assert@1.4.1
  | +-- browserify-zlib@0.1.4
  | | `-- pako@0.2.9
  | +-- buffer@4.9.1
  | | +-- base64-js@1.2.0
  | |`-- ieee754@1.1.6
  | +-- console-browserify@1.1.0
  | | `-- date-now@0.1.4
  | +-- constants-browserify@0.0.1
  | +-- crypto-browserify@3.2.8
  | | +-- pbkdf2-compat@2.0.1
  | | +-- ripemd160@0.2.0
  | |`-- sha.js@2.2.6
  | +-- domain-browser@1.1.7
  | +-- events@1.1.1
  | +-- http-browserify@1.7.0
  | | `-- Base64@0.2.1
  | +-- https-browserify@0.0.0
  | +-- os-browserify@0.1.2
  | +-- path-browserify@0.0.0
  | +-- process@0.11.9
  | +-- punycode@1.4.1
  | +-- querystring-es3@0.2.1
  | +-- readable-stream@1.1.14
  | |`-- isarray@0.0.1
  | +-- stream-browserify@1.0.0
  | | `-- readable-stream@1.1.14
  | |`-- isarray@0.0.1
  | +-- string_decoder@0.10.31
  | +-- timers-browserify@1.4.2
  | +-- tty-browserify@0.0.0
  | +-- url@0.10.3
  | | +-- punycode@1.3.2
  | | `-- querystring@0.2.0
  | +-- util@0.10.3
  | |`-- inherits@2.0.1
  | `-- vm-browserify@0.0.4
  |`-- indexof@0.0.1
  +-- optimist@0.6.1
  | +-- minimist@0.0.10
  | `-- wordwrap@0.0.3
  +-- supports-color@3.1.2
  |`-- has-flag@1.0.0
  +-- tapable@0.1.10
  +-- uglify-js@2.6.4
  | +-- async@0.2.10
  | +-- source-map@0.5.6
  | +-- uglify-to-browserify@1.0.2
  | `-- yargs@3.10.0
  |   +-- camelcase@1.2.1
  |   +-- cliui@2.1.0
  |   | +-- center-align@0.1.3
  |   | | +-- align-text@0.1.4
  |   | | | +-- longest@1.0.1
  |   | | |`-- repeat-string@1.5.4
  |   | | `-- lazy-cache@1.0.4
  |   | +-- right-align@0.1.3
  |   |`-- wordwrap@0.0.2
  |   +-- decamelize@1.2.0
  |   `-- window-size@0.1.0
  +-- watchpack@0.2.9
  | +-- async@0.9.2
  |`-- chokidar@1.6.0
  |   +-- anymatch@1.3.0
  |   | `-- micromatch@2.3.11
  |   |   +-- arr-diff@2.0.0
  |   |   |`-- arr-flatten@1.0.1
  |   |   +-- array-unique@0.2.1
  |   |   +-- braces@1.8.5
  |   |   | +-- expand-range@1.8.2
  |   |   | | `-- fill-range@2.2.3
  |   |   | |   +-- is-number@2.1.0
  |   |   | |`-- randomatic@1.1.5
  |   |   | +-- preserve@0.2.0
  |   |   | `-- repeat-element@1.1.2
  |   |   +-- expand-brackets@0.1.5
  |   |   |`-- is-posix-bracket@0.1.1
  |   |   +-- extglob@0.3.2
  |   |   +-- filename-regex@2.0.0
  |   |   +-- kind-of@3.0.4
  |   |   | `-- is-buffer@1.1.4
  |   |   +-- normalize-path@2.0.1
  |   |   +-- object.omit@2.0.0
  |   |   | +-- for-own@0.1.4
  |   |   | |`-- for-in@0.1.6
  |   |   | `-- is-extendable@0.1.1
  |   |   +-- parse-glob@3.0.4
  |   |   | +-- glob-base@0.3.0
  |   |   |`-- is-dotfile@1.0.2
  |   |   `-- regex-cache@0.4.3
  |   |     +-- is-equal-shallow@0.1.3
  |   |`-- is-primitive@2.0.0
  |   +-- async-each@1.0.1
  |   +-- glob-parent@2.0.0
  |   +-- is-binary-path@1.0.1
  |   | `-- binary-extensions@1.6.0
  |   +-- is-glob@2.0.1
  |   |`-- is-extglob@1.0.0
  |   +-- path-is-absolute@1.0.0
  |   `-- readdirp@2.1.0
  |`-- set-immediate-shim@1.0.1
  `-- webpack-core@0.6.8
`-- source-list-map@0.1.6

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm WARN @angular/compiler-cli@0.6.0 requires a peer of typescript@^2.0.2 but no
ne was installed.
npm WARN @angular/compiler-cli@0.6.0 requires a peer of @angular/platform-server
@^2.0.0-rc.6 but none was installed.
npm WARN @angular/tsc-wrapped@0.3.0 requires a peer of typescript@^2.0.2 but non
e was installed.
npm WARN tsickle@0.1.7 requires a peer of typescript@^2.0.0 || ^2.1.0-dev but no
ne was installed.
npm WARN primeng-quickstart-webpack@1.0.0-SNAPSHOT No repository field.

C:\Users\A\Desktop\TESTS\primeng-quickstart-webpack-master>npm start

> primeng-quickstart-webpack@1.0.0-SNAPSHOT start C:\Users\A\Desktop\TESTS\prime
> ng-quickstart-webpack-master
> npm run tsc && npm run webpack-dev-server
> 
> primeng-quickstart-webpack@1.0.0-SNAPSHOT tsc C:\Users\A\Desktop\TESTS\primeng
> -quickstart-webpack-master
> tsc
> 
> primeng-quickstart-webpack@1.0.0-SNAPSHOT webpack-dev-server C:\Users\A\Deskto
> p\TESTS\primeng-quickstart-webpack-master
> webpack-dev-server

'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\A\AppData\Roam
ing\npm\node_modules\npm\bin\npm-cli.js" "run" "webpack-dev-server"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! primeng-quickstart-webpack@1.0.0-SNAPSHOT webpack-dev-server: `webpack-
dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the primeng-quickstart-webpack@1.0.0-SNAPSHOT webpack-dev-ser
ver script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the primeng-quickstart-we
bpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs primeng-quickstart-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls primeng-quickstart-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\A\Desktop\TESTS\primeng-quickstart-webpack-master\npm-debu
g.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\A\AppData\Roam
ing\npm\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! primeng-quickstart-webpack@1.0.0-SNAPSHOT start: `npm run tsc && npm ru
n webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the primeng-quickstart-webpack@1.0.0-SNAPSHOT start script 'n
pm run tsc && npm run webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the primeng-quickstart-we
bpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run tsc && npm run webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs primeng-quickstart-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls primeng-quickstart-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\A\Desktop\TESTS\primeng-quickstart-webpack-master\npm-debu
g.log

C:\Users\A\Desktop\TESTS\primeng-quickstart-webpack-master>

**Comment by sudheerj** [comment]
Now the dependency available for Dev server.
