### ISSUE TITLE
error TS5023: Unknown compiler option 'moduleResolution'.

### ISSUE THREAD

**Issue by ikostov** [primefaces/primeng-quickstart-webpack#9]
It seems README.md is missing a few steps, would you please update it, or is there something else that's missing?

$ npm start

> primeng-quickstart-webpack@1.0.0-SNAPSHOT start D:\dev\webpack\primeng-quickstart-webpack
> npm run tsc && npm run webpack-dev-server
> 
> primeng-quickstart-webpack@1.0.0-SNAPSHOT tsc D:\dev\webpack\primeng-quickstart-webpack
> tsc

error TS5023: Unknown compiler option 'moduleResolution'.

npm ERR! Windows_NT 6.1.7601
npm ERR! node v6.5.0
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! primeng-quickstart-webpack@1.0.0-SNAPSHOT tsc: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the primeng-quickstart-webpack@1.0.0-SNAPSHOT tsc script 'tsc'.

**Comment by aluanhaddad** [comment]
run `tsc --version`

**Comment by ikostov** [comment]
It seems typescript was not installed.
> tsc --version
Version 2.2.1

Funny thing now is that webpack.config.js requires ./config/webpack.dev.js but there is neither a config folder nor a webpack.dev.js anywhere to be found.

**Comment by sudheerj** [comment]
The project updated with tsc and webpack.dev.js configurations.
